import Head from 'next/head'

import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useContext } from 'react';
import { AuthContext } from '@/context/AuthContext';
import DefaultTabs from '@/components/DefaultTabs';
import Welcome from '@/components/Welcome';

import Upload from '@/components/Upload';
import YourUpload from '@/components/YourUpload';
import OpenRequest from '@/components/OpenRequest';
// import styles from '@/styles/Home.module.css'




export default function Home() {
  const UserTabs = ["Your Uploads","Open Requests"]
  const TabComponents = [<YourUpload/>,<OpenRequest/>]
  const {isDisconnected,ensName} = useContext(AuthContext)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {isDisconnected && <ConnectButton/>}
        {!isDisconnected && 
        <div className='md:w-3/4 w-full m-auto p-4'>
          <Welcome/>
        <DefaultTabs tabs = {UserTabs} tabC = {TabComponents}/>
        {/* <Upload/> */}
          </div>}
        {/* <DefaultTable/> */}

      </main>
    </>
  )
}
